travis:
  secure:
    BINSTAR_TOKEN: MrlkC1eNRvKFExf7taCc2HlNhlVJXP85iSs7aBlVeo3a/yalIjSP206i8p/bXeInV2gNnn8+/v/YexPIZKvx8NN1H4suZuEnQdiVrn/Yavc4LRh+POmfNrHlFswuIqCZNeMMxrMc1MZzz61HnX2ch6gSh0RmRdeTzQfHPMK5HBPuwmGeVxmDaIQCUs6lDDi7CW6MVQA5Gd2RwPQ7TEcO0UTo9o65GASmcbIqsRT/mAOzDMWwi9cmG2FWgbgQ4QUuXG23FkrYD6cZrBGUTI01K8kt6fnZClKDQzaMsBbYSpMG1fkFKmkFIRtEsByOdFv+72Bbh474wHCjuiPfP21jaUqnZKIIcdfnyjujxHVgNiJiekIq8Jt27k/4wadcE+0BhRwW1KDi7jnqBzEp6oIqNx3LAMi169lzVDJ7Z4GdnJKXj+oqdXTJAbd7blp5MROUnugdTmHKpjQpwUIQIKoHnL6NOTbaXxWKPwXINJY9pcSd8T6hJsXNrC41G2pb+EQJv+ze7usMzYdVuLq1PqWD666TGxBPr4nwLcDH1N562rnTqQN6X8AWnMH0x/70AaSJ+cyo6uhvwyXZzpFXKB6VY8Eys/JKyUqOtRUUvmlf3en9KiEP0uMrExyhhTdBmngzNrPxTvyj/98vDNoryKerbRvolse6eYL1TiqoNtnFg/g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
